[solution]
name = "moe-v2-zerocopy-noatomic"
definition = "moe_fp8_block_scale_ds_routing_topk8_ng8_kg4_e32_h7168_i2048"
author = "LIGHTSPEED/prateek,nirmal"

[build]
language = "triton"
entry_point = "kernel.py::kernel"
binding = "torch"
