// Auto-generated by scripts/update_dashboard_data.py — do not edit manually
window.EXPERIMENTS = [
  {
    "folder": "round_000_c150589_baseline",
    "config": {
      "round": 0,
      "commit": "c150589",
      "ts": "2026-03-27",
      "note": "V6 baseline \u2014 FP8 GEMM1+GEMM2 medium/large, FP32 GEMM2 tiny/small",
      "tier": "all",
      "strategy": "baseline",
      "changes": "Initial V6: workload-tiered dispatch + FP8 tensor cores on B200 (SM10)"
    },
    "results": {
      "round": 0,
      "commit": "c150589",
      "ts": "2026-03-27",
      "all_passed": true,
      "avg_speedup": 16.27,
      "workloads": [
        {
          "uuid": "e05c6c03",
          "tier": "tiny",
          "seq": 1,
          "status": "PASSED",
          "lat_ms": 0.541,
          "speedup": 20.68,
          "max_abs_err": 2050.0,
          "max_rel_err": 9.31
        },
        {
          "uuid": "8f1ff9f1",
          "tier": "small",
          "seq": 80,
          "status": "PASSED",
          "lat_ms": 0.862,
          "speedup": 18.42,
          "max_abs_err": 4100.0,
          "max_rel_err": 820.0
        },
        {
          "uuid": "1a4c6ba1",
          "tier": "medium",
          "seq": 901,
          "status": "PASSED",
          "lat_ms": 1.096,
          "speedup": 19.26,
          "max_abs_err": 410000.0,
          "max_rel_err": 41000000000000.0
        },
        {
          "uuid": "5e8dc11c",
          "tier": "large",
          "seq": 14107,
          "status": "PASSED",
          "lat_ms": 6.656,
          "speedup": 6.77,
          "max_abs_err": 582000.0,
          "max_rel_err": 53700000000000.0
        }
      ]
    },
    "ncu": {
      "round": 0,
      "commit": "c150589",
      "ts": "2026-03-29 06:32 UTC",
      "note": "V6 baseline",
      "source": "NCU/mar27",
      "kernels": [
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 0.03,
          "hbm_pct": null,
          "l1_pct": 37.11,
          "warp_pct": 1.58,
          "tier": "tiny",
          "seq": 1
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.1,
          "sm_pct": 6.8,
          "hbm_pct": null,
          "l1_pct": 1.15,
          "warp_pct": 6.27,
          "tier": "tiny",
          "seq": 1
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.1,
          "sm_pct": 29.82,
          "hbm_pct": null,
          "l1_pct": 1.84,
          "warp_pct": 7.33,
          "tier": "tiny",
          "seq": 1
        },
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 1.73,
          "hbm_pct": null,
          "l1_pct": 40.87,
          "warp_pct": 1.56,
          "tier": "small",
          "seq": 80
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.4,
          "sm_pct": 42.47,
          "hbm_pct": null,
          "l1_pct": 3.81,
          "warp_pct": 12.48,
          "tier": "small",
          "seq": 80
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.4,
          "sm_pct": 40.32,
          "hbm_pct": null,
          "l1_pct": 3.06,
          "warp_pct": 12.49,
          "tier": "small",
          "seq": 80
        },
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 17.53,
          "hbm_pct": null,
          "l1_pct": 54.7,
          "warp_pct": 7.74,
          "tier": "medium",
          "seq": 901
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.4,
          "sm_pct": 31.25,
          "hbm_pct": null,
          "l1_pct": 3.81,
          "warp_pct": 12.51,
          "tier": "medium",
          "seq": 901
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.6,
          "sm_pct": 40.43,
          "hbm_pct": null,
          "l1_pct": 2.91,
          "warp_pct": 24.23,
          "tier": "medium",
          "seq": 901
        },
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 72.89,
          "hbm_pct": null,
          "l1_pct": 22.68,
          "warp_pct": 68.94,
          "tier": "large",
          "seq": 14107
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.0,
          "sm_pct": 34.83,
          "hbm_pct": null,
          "l1_pct": 5.0,
          "warp_pct": 12.56,
          "tier": "large",
          "seq": 14107
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.0,
          "sm_pct": 49.01,
          "hbm_pct": null,
          "l1_pct": 1.73,
          "warp_pct": 22.15,
          "tier": "large",
          "seq": 14107
        },
        {
          "kernel_raw": "_reduce_kernel",
          "kernel": "_reduce_kernel",
          "dur_us": 0.0,
          "sm_pct": 71.83,
          "hbm_pct": null,
          "l1_pct": 19.79,
          "warp_pct": 90.26,
          "tier": "large",
          "seq": 14107
        }
      ]
    },
    "notes": "# Round 0 \u2014 Baseline (V6)\n\n**Commit**: c150589\n**Date**: 2026-03-27\n**Strategy**: Baseline \u2014 FP8 GEMM1+GEMM2 for medium/large, FP32 GEMM2 for tiny/small\n\n## Results\n\n| Tier | seq | lat(ms) | speedup | Status |\n|------|----:|--------:|--------:|--------|\n| tiny | 1 | 0.541 | 20.68x | PASSED |\n| small | 80 | 0.862 | 18.42x | PASSED |\n| medium | 901 | 1.096 | 19.26x | PASSED |\n| large | 14107 | 6.656 | 6.77x | PASSED |\n\n**Avg speedup**: 16.27x\n\n## Observations\n\n- Large tier at 6.77x is the clear bottleneck vs 18\u201321x for other tiers.\n- GEMM2 large: 6195\u03bcs, 49% SM, 1.7% L1 \u2014 deep HBM-latency bound.\n- Medium/tiny/small all excellent (18\u201321x).\n- NCU from mar27 is pre-FP8 GEMM2 for medium/large \u2014 fresh profiling needed.\n\n## Hypothesis for Round 1\n\nLarge GEMM2: try BM=32\u219264 with stages=4.\nsmem: (64+128)\u00d7128\u00d71\u00d74\u00d72 = 192KB < 232KB \u2192 2 CTAs/SM \u2713\nArithmetic intensity: 51\u219289 FLOPS/byte \u2014 expect \u226510% speedup.\n"
  },
  {
    "folder": "round_001_6f86f66_large_gemm2_bm64_stages4",
    "config": {
      "round": 1,
      "commit": "6f86f66",
      "ts": "2026-03-29 06:01 UTC",
      "note": "large GEMM2 BM=64 stages=4",
      "tier": "all",
      "strategy": "optimization",
      "changes": "large GEMM2 BM=64 stages=4"
    },
    "results": {
      "round": 1,
      "commit": "6f86f66",
      "ts": "2026-03-29 06:01 UTC",
      "all_passed": false,
      "avg_speedup": 17.48,
      "workloads": [
        {
          "uuid": "e05c6c03",
          "tier": "tiny",
          "seq": 1,
          "status": "PASSED",
          "lat_ms": 0.6152202248573303,
          "speedup": 17.9792392376026,
          "max_abs_err": 2048.0,
          "max_rel_err": 4.102362155914307
        },
        {
          "uuid": "8f1ff9f1",
          "tier": "small",
          "seq": 80,
          "status": "PASSED",
          "lat_ms": 0.9302833914756775,
          "speedup": 16.97590612204002,
          "max_abs_err": 4096.0,
          "max_rel_err": 113.90255737304688
        },
        {
          "uuid": "1a4c6ba1",
          "tier": "medium",
          "seq": 901,
          "status": "INCORRECT_NUMERICAL",
          "lat_ms": null,
          "speedup": null,
          "max_abs_err": 325632.0,
          "max_rel_err": 32563200524288.0
        },
        {
          "uuid": "5e8dc11c",
          "tier": "large",
          "seq": 14107,
          "status": "INCORRECT_NUMERICAL",
          "lat_ms": null,
          "speedup": null,
          "max_abs_err": 528384.0,
          "max_rel_err": 48742401048576.0
        }
      ]
    },
    "ncu": {
      "round": 1,
      "commit": "6f86f66",
      "ts": "2026-03-29 06:32 UTC",
      "note": "large GEMM2 BM=64 stages=4",
      "source": "NCU/mar27",
      "kernels": [
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 0.03,
          "hbm_pct": null,
          "l1_pct": 37.11,
          "warp_pct": 1.58,
          "tier": "tiny",
          "seq": 1
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.1,
          "sm_pct": 6.8,
          "hbm_pct": null,
          "l1_pct": 1.15,
          "warp_pct": 6.27,
          "tier": "tiny",
          "seq": 1
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.1,
          "sm_pct": 29.82,
          "hbm_pct": null,
          "l1_pct": 1.84,
          "warp_pct": 7.33,
          "tier": "tiny",
          "seq": 1
        },
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 1.73,
          "hbm_pct": null,
          "l1_pct": 40.87,
          "warp_pct": 1.56,
          "tier": "small",
          "seq": 80
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.4,
          "sm_pct": 42.47,
          "hbm_pct": null,
          "l1_pct": 3.81,
          "warp_pct": 12.48,
          "tier": "small",
          "seq": 80
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.4,
          "sm_pct": 40.32,
          "hbm_pct": null,
          "l1_pct": 3.06,
          "warp_pct": 12.49,
          "tier": "small",
          "seq": 80
        },
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 17.53,
          "hbm_pct": null,
          "l1_pct": 54.7,
          "warp_pct": 7.74,
          "tier": "medium",
          "seq": 901
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.4,
          "sm_pct": 31.25,
          "hbm_pct": null,
          "l1_pct": 3.81,
          "warp_pct": 12.51,
          "tier": "medium",
          "seq": 901
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.6,
          "sm_pct": 40.43,
          "hbm_pct": null,
          "l1_pct": 2.91,
          "warp_pct": 24.23,
          "tier": "medium",
          "seq": 901
        },
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 72.89,
          "hbm_pct": null,
          "l1_pct": 22.68,
          "warp_pct": 68.94,
          "tier": "large",
          "seq": 14107
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.0,
          "sm_pct": 34.83,
          "hbm_pct": null,
          "l1_pct": 5.0,
          "warp_pct": 12.56,
          "tier": "large",
          "seq": 14107
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.0,
          "sm_pct": 49.01,
          "hbm_pct": null,
          "l1_pct": 1.73,
          "warp_pct": 22.15,
          "tier": "large",
          "seq": 14107
        },
        {
          "kernel_raw": "_reduce_kernel",
          "kernel": "_reduce_kernel",
          "dur_us": 0.0,
          "sm_pct": 71.83,
          "hbm_pct": null,
          "l1_pct": 19.79,
          "warp_pct": 90.26,
          "tier": "large",
          "seq": 14107
        }
      ]
    },
    "notes": "# Round 1 \u2014 large GEMM2 BM=64 stages=4\n\n**Commit**: 6f86f66\n**Date**: 2026-03-29 06:01 UTC\n\n## Results\n\n| Tier | seq | lat(ms) | speedup | Status |\n|------|----:|--------:|--------:|--------|\n| tiny | 1 | 0.615 | 17.98x | PASSED |\n| small | 80 | 0.930 | 16.98x | PASSED |\n| medium | 901 | N/A | N/A | INCORRECT_NUMERICAL |\n| large | 14107 | N/A | N/A | INCORRECT_NUMERICAL |\n\n**Avg speedup**: 17.48x\n\n## Observations\n\n_[fill in after reviewing results]_\n\n## Hypothesis for Next Run\n\n_[fill in before starting next round]_"
  },
  {
    "folder": "round_002_8e31f99_true_fp32_baseline_confirm",
    "config": {
      "round": 2,
      "commit": "8e31f99",
      "ts": "2026-03-29 06:06 UTC",
      "note": "true FP32 baseline confirm",
      "tier": "all",
      "strategy": "optimization",
      "changes": "true FP32 baseline confirm"
    },
    "results": {
      "round": 2,
      "commit": "8e31f99",
      "ts": "2026-03-29 06:06 UTC",
      "all_passed": true,
      "avg_speedup": 15.45,
      "workloads": [
        {
          "uuid": "e05c6c03",
          "tier": "tiny",
          "seq": 1,
          "status": "PASSED",
          "lat_ms": 0.5950594557523727,
          "speedup": 18.72215677822031,
          "max_abs_err": 2048.0,
          "max_rel_err": 9.859437942504883
        },
        {
          "uuid": "8f1ff9f1",
          "tier": "small",
          "seq": 80,
          "status": "PASSED",
          "lat_ms": 0.9108719350099564,
          "speedup": 17.52118384249603,
          "max_abs_err": 4096.0,
          "max_rel_err": 1034.1300048828125
        },
        {
          "uuid": "1a4c6ba1",
          "tier": "medium",
          "seq": 901,
          "status": "PASSED",
          "lat_ms": 1.132658050060272,
          "speedup": 18.60883821379211,
          "max_abs_err": 344064.0,
          "max_rel_err": 33996801048576.0
        },
        {
          "uuid": "5e8dc11c",
          "tier": "large",
          "seq": 14107,
          "status": "PASSED",
          "lat_ms": 6.499548414230347,
          "speedup": 6.950642869555088,
          "max_abs_err": 561152.0,
          "max_rel_err": 50790400000000.0
        }
      ]
    },
    "ncu": {
      "round": 2,
      "commit": "8e31f99",
      "ts": "2026-03-29 06:32 UTC",
      "note": "true FP32 baseline confirm",
      "source": "NCU/mar27",
      "kernels": [
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 0.03,
          "hbm_pct": null,
          "l1_pct": 37.11,
          "warp_pct": 1.58,
          "tier": "tiny",
          "seq": 1
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.1,
          "sm_pct": 6.8,
          "hbm_pct": null,
          "l1_pct": 1.15,
          "warp_pct": 6.27,
          "tier": "tiny",
          "seq": 1
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.1,
          "sm_pct": 29.82,
          "hbm_pct": null,
          "l1_pct": 1.84,
          "warp_pct": 7.33,
          "tier": "tiny",
          "seq": 1
        },
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 1.73,
          "hbm_pct": null,
          "l1_pct": 40.87,
          "warp_pct": 1.56,
          "tier": "small",
          "seq": 80
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.4,
          "sm_pct": 42.47,
          "hbm_pct": null,
          "l1_pct": 3.81,
          "warp_pct": 12.48,
          "tier": "small",
          "seq": 80
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.4,
          "sm_pct": 40.32,
          "hbm_pct": null,
          "l1_pct": 3.06,
          "warp_pct": 12.49,
          "tier": "small",
          "seq": 80
        },
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 17.53,
          "hbm_pct": null,
          "l1_pct": 54.7,
          "warp_pct": 7.74,
          "tier": "medium",
          "seq": 901
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.4,
          "sm_pct": 31.25,
          "hbm_pct": null,
          "l1_pct": 3.81,
          "warp_pct": 12.51,
          "tier": "medium",
          "seq": 901
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.6,
          "sm_pct": 40.43,
          "hbm_pct": null,
          "l1_pct": 2.91,
          "warp_pct": 24.23,
          "tier": "medium",
          "seq": 901
        },
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 72.89,
          "hbm_pct": null,
          "l1_pct": 22.68,
          "warp_pct": 68.94,
          "tier": "large",
          "seq": 14107
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.0,
          "sm_pct": 34.83,
          "hbm_pct": null,
          "l1_pct": 5.0,
          "warp_pct": 12.56,
          "tier": "large",
          "seq": 14107
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.0,
          "sm_pct": 49.01,
          "hbm_pct": null,
          "l1_pct": 1.73,
          "warp_pct": 22.15,
          "tier": "large",
          "seq": 14107
        },
        {
          "kernel_raw": "_reduce_kernel",
          "kernel": "_reduce_kernel",
          "dur_us": 0.0,
          "sm_pct": 71.83,
          "hbm_pct": null,
          "l1_pct": 19.79,
          "warp_pct": 90.26,
          "tier": "large",
          "seq": 14107
        }
      ]
    },
    "notes": "# Round 2 \u2014 true FP32 baseline confirm\n\n**Commit**: 8e31f99\n**Date**: 2026-03-29 06:06 UTC\n\n## Results\n\n| Tier | seq | lat(ms) | speedup | Status |\n|------|----:|--------:|--------:|--------|\n| tiny | 1 | 0.595 | 18.72x | PASSED |\n| small | 80 | 0.911 | 17.52x | PASSED |\n| medium | 901 | 1.133 | 18.61x | PASSED |\n| large | 14107 | 6.500 | 6.95x | PASSED |\n\n**Avg speedup**: 15.45x\n\n## Observations\n\n_[fill in after reviewing results]_\n\n## Hypothesis for Next Run\n\n_[fill in before starting next round]_"
  },
  {
    "folder": "round_003_2fe5aff_large_gemm1_s3-5_gemm2_s6-7_deeper_pi",
    "config": {
      "round": 3,
      "commit": "2fe5aff",
      "ts": "2026-03-29 06:16 UTC",
      "note": "large GEMM1 s3->5, GEMM2 s6->7 deeper pipeline",
      "tier": "all",
      "strategy": "optimization",
      "changes": "large GEMM1 s3->5, GEMM2 s6->7 deeper pipeline"
    },
    "results": {
      "round": 3,
      "commit": "2fe5aff",
      "ts": "2026-03-29 06:16 UTC",
      "all_passed": true,
      "avg_speedup": 15.42,
      "workloads": [
        {
          "uuid": "e05c6c03",
          "tier": "tiny",
          "seq": 1,
          "status": "PASSED",
          "lat_ms": 0.5943400316238403,
          "speedup": 18.78676656467446,
          "max_abs_err": 2048.0,
          "max_rel_err": 2.094444513320923
        },
        {
          "uuid": "8f1ff9f1",
          "tier": "small",
          "seq": 80,
          "status": "PASSED",
          "lat_ms": 0.9138157436847687,
          "speedup": 17.389530871309567,
          "max_abs_err": 4096.0,
          "max_rel_err": 176.2307586669922
        },
        {
          "uuid": "1a4c6ba1",
          "tier": "medium",
          "seq": 901,
          "status": "PASSED",
          "lat_ms": 1.1374931182861328,
          "speedup": 18.58295514000215,
          "max_abs_err": 503808.0,
          "max_rel_err": 37887999475712.0
        },
        {
          "uuid": "5e8dc11c",
          "tier": "large",
          "seq": 14107,
          "status": "PASSED",
          "lat_ms": 6.509025143623352,
          "speedup": 6.932917416545512,
          "max_abs_err": 561152.0,
          "max_rel_err": 56115198951424.0
        }
      ]
    },
    "ncu": {
      "round": 3,
      "commit": "2fe5aff",
      "ts": "2026-03-29 06:32 UTC",
      "note": "large GEMM1 s3->5, GEMM2 s6->7",
      "source": "NCU/mar27",
      "kernels": [
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 0.03,
          "hbm_pct": null,
          "l1_pct": 37.11,
          "warp_pct": 1.58,
          "tier": "tiny",
          "seq": 1
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.1,
          "sm_pct": 6.8,
          "hbm_pct": null,
          "l1_pct": 1.15,
          "warp_pct": 6.27,
          "tier": "tiny",
          "seq": 1
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.1,
          "sm_pct": 29.82,
          "hbm_pct": null,
          "l1_pct": 1.84,
          "warp_pct": 7.33,
          "tier": "tiny",
          "seq": 1
        },
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 1.73,
          "hbm_pct": null,
          "l1_pct": 40.87,
          "warp_pct": 1.56,
          "tier": "small",
          "seq": 80
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.4,
          "sm_pct": 42.47,
          "hbm_pct": null,
          "l1_pct": 3.81,
          "warp_pct": 12.48,
          "tier": "small",
          "seq": 80
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.4,
          "sm_pct": 40.32,
          "hbm_pct": null,
          "l1_pct": 3.06,
          "warp_pct": 12.49,
          "tier": "small",
          "seq": 80
        },
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 17.53,
          "hbm_pct": null,
          "l1_pct": 54.7,
          "warp_pct": 7.74,
          "tier": "medium",
          "seq": 901
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.4,
          "sm_pct": 31.25,
          "hbm_pct": null,
          "l1_pct": 3.81,
          "warp_pct": 12.51,
          "tier": "medium",
          "seq": 901
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.6,
          "sm_pct": 40.43,
          "hbm_pct": null,
          "l1_pct": 2.91,
          "warp_pct": 24.23,
          "tier": "medium",
          "seq": 901
        },
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 72.89,
          "hbm_pct": null,
          "l1_pct": 22.68,
          "warp_pct": 68.94,
          "tier": "large",
          "seq": 14107
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.0,
          "sm_pct": 34.83,
          "hbm_pct": null,
          "l1_pct": 5.0,
          "warp_pct": 12.56,
          "tier": "large",
          "seq": 14107
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.0,
          "sm_pct": 49.01,
          "hbm_pct": null,
          "l1_pct": 1.73,
          "warp_pct": 22.15,
          "tier": "large",
          "seq": 14107
        },
        {
          "kernel_raw": "_reduce_kernel",
          "kernel": "_reduce_kernel",
          "dur_us": 0.0,
          "sm_pct": 71.83,
          "hbm_pct": null,
          "l1_pct": 19.79,
          "warp_pct": 90.26,
          "tier": "large",
          "seq": 14107
        }
      ]
    },
    "notes": "# Round 3 \u2014 large GEMM1 s3->5, GEMM2 s6->7 deeper pipeline\n\n**Commit**: 2fe5aff\n**Date**: 2026-03-29 06:16 UTC\n\n## Results\n\n| Tier | seq | lat(ms) | speedup | Status |\n|------|----:|--------:|--------:|--------|\n| tiny | 1 | 0.594 | 18.79x | PASSED |\n| small | 80 | 0.914 | 17.39x | PASSED |\n| medium | 901 | 1.137 | 18.58x | PASSED |\n| large | 14107 | 6.509 | 6.93x | PASSED |\n\n**Avg speedup**: 15.42x\n\n## Observations\n\n_[fill in after reviewing results]_\n\n## Hypothesis for Next Run\n\n_[fill in before starting next round]_"
  },
  {
    "folder": "round_004_fcc06bf_large_gemm2_bm64_fp32_halves_b_reads",
    "config": {
      "round": 4,
      "commit": "fcc06bf",
      "ts": "2026-03-29 06:25 UTC",
      "note": "large GEMM2 BM=64 FP32, halves B reads",
      "tier": "all",
      "strategy": "optimization",
      "changes": "large GEMM2 BM=64 FP32, halves B reads"
    },
    "results": {
      "round": 4,
      "commit": "fcc06bf",
      "ts": "2026-03-29 06:25 UTC",
      "all_passed": true,
      "avg_speedup": 16.49,
      "workloads": [
        {
          "uuid": "e05c6c03",
          "tier": "tiny",
          "seq": 1,
          "status": "PASSED",
          "lat_ms": 0.5487767682075501,
          "speedup": 20.061478391736426,
          "max_abs_err": 2048.0,
          "max_rel_err": 11.378947257995605
        },
        {
          "uuid": "8f1ff9f1",
          "tier": "small",
          "seq": 80,
          "status": "PASSED",
          "lat_ms": 0.8898919678926468,
          "speedup": 17.746414659944143,
          "max_abs_err": 4096.0,
          "max_rel_err": 303.39996337890625
        },
        {
          "uuid": "1a4c6ba1",
          "tier": "medium",
          "seq": 901,
          "status": "PASSED",
          "lat_ms": 1.105189888715744,
          "speedup": 18.932741406637927,
          "max_abs_err": 350208.0,
          "max_rel_err": 35020800524288.0
        },
        {
          "uuid": "5e8dc11c",
          "tier": "large",
          "seq": 14107,
          "status": "PASSED",
          "lat_ms": 4.893861184120178,
          "speedup": 9.2008734287094,
          "max_abs_err": 512000.0,
          "max_rel_err": 50176001572864.0
        }
      ]
    },
    "ncu": {
      "round": 4,
      "commit": "fcc06bf",
      "ts": "2026-03-29 06:46 UTC",
      "note": "large GEMM2 BM=64 FP32 halves B reads",
      "source": "NCU/mar27",
      "kernels": [
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 0.03,
          "hbm_pct": null,
          "l1_pct": 37.11,
          "warp_pct": 1.58,
          "tier": "tiny",
          "seq": 1
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.1,
          "sm_pct": 6.8,
          "hbm_pct": null,
          "l1_pct": 1.15,
          "warp_pct": 6.27,
          "tier": "tiny",
          "seq": 1
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.1,
          "sm_pct": 29.82,
          "hbm_pct": null,
          "l1_pct": 1.84,
          "warp_pct": 7.33,
          "tier": "tiny",
          "seq": 1
        },
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 1.73,
          "hbm_pct": null,
          "l1_pct": 40.87,
          "warp_pct": 1.56,
          "tier": "small",
          "seq": 80
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.4,
          "sm_pct": 42.47,
          "hbm_pct": null,
          "l1_pct": 3.81,
          "warp_pct": 12.48,
          "tier": "small",
          "seq": 80
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.4,
          "sm_pct": 40.32,
          "hbm_pct": null,
          "l1_pct": 3.06,
          "warp_pct": 12.49,
          "tier": "small",
          "seq": 80
        },
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 17.53,
          "hbm_pct": null,
          "l1_pct": 54.7,
          "warp_pct": 7.74,
          "tier": "medium",
          "seq": 901
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.4,
          "sm_pct": 31.25,
          "hbm_pct": null,
          "l1_pct": 3.81,
          "warp_pct": 12.51,
          "tier": "medium",
          "seq": 901
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.6,
          "sm_pct": 40.43,
          "hbm_pct": null,
          "l1_pct": 2.91,
          "warp_pct": 24.23,
          "tier": "medium",
          "seq": 901
        },
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 72.89,
          "hbm_pct": null,
          "l1_pct": 22.68,
          "warp_pct": 68.94,
          "tier": "large",
          "seq": 14107
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.0,
          "sm_pct": 34.83,
          "hbm_pct": null,
          "l1_pct": 5.0,
          "warp_pct": 12.56,
          "tier": "large",
          "seq": 14107
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.0,
          "sm_pct": 49.01,
          "hbm_pct": null,
          "l1_pct": 1.73,
          "warp_pct": 22.15,
          "tier": "large",
          "seq": 14107
        },
        {
          "kernel_raw": "_reduce_kernel",
          "kernel": "_reduce_kernel",
          "dur_us": 0.0,
          "sm_pct": 71.83,
          "hbm_pct": null,
          "l1_pct": 19.79,
          "warp_pct": 90.26,
          "tier": "large",
          "seq": 14107
        }
      ]
    },
    "notes": "# Round 4 \u2014 large GEMM2 BM=64 FP32, halves B reads\n\n**Commit**: fcc06bf\n**Date**: 2026-03-29 06:25 UTC\n\n## Results\n\n| Tier | seq | lat(ms) | speedup | Status |\n|------|----:|--------:|--------:|--------|\n| tiny | 1 | 0.549 | 20.06x | PASSED |\n| small | 80 | 0.890 | 17.75x | PASSED |\n| medium | 901 | 1.105 | 18.93x | PASSED |\n| large | 14107 | 4.894 | 9.20x | PASSED |\n\n**Avg speedup**: 16.49x\n\n## Observations\n\n_[fill in after reviewing results]_\n\n## Hypothesis for Next Run\n\n_[fill in before starting next round]_"
  },
  {
    "folder": "round_005_8ee1ca1_large_bf16_act_gemm2_s7",
    "config": {
      "round": 5,
      "commit": "8ee1ca1",
      "ts": "2026-03-29 06:37 UTC",
      "note": "large BF16 act, GEMM2 s7",
      "tier": "all",
      "strategy": "optimization",
      "changes": "large BF16 act, GEMM2 s7"
    },
    "results": {
      "round": 5,
      "commit": "8ee1ca1",
      "ts": "2026-03-29 06:37 UTC",
      "all_passed": false,
      "avg_speedup": 17.61,
      "workloads": [
        {
          "uuid": "e05c6c03",
          "tier": "tiny",
          "seq": 1,
          "status": "PASSED",
          "lat_ms": 0.6277404810190201,
          "speedup": 17.851862434763067,
          "max_abs_err": 2048.0,
          "max_rel_err": 40.24528121948242
        },
        {
          "uuid": "8f1ff9f1",
          "tier": "small",
          "seq": 80,
          "status": "PASSED",
          "lat_ms": 0.9445678086280823,
          "speedup": 16.846056045382824,
          "max_abs_err": 4096.0,
          "max_rel_err": 126.0921859741211
        },
        {
          "uuid": "1a4c6ba1",
          "tier": "medium",
          "seq": 901,
          "status": "PASSED",
          "lat_ms": 1.1655623693466186,
          "speedup": 18.121973674356592,
          "max_abs_err": 374784.0,
          "max_rel_err": 37478400524288.0
        },
        {
          "uuid": "5e8dc11c",
          "tier": "large",
          "seq": 14107,
          "status": "RUNTIME_ERROR",
          "lat_ms": null,
          "speedup": null,
          "max_abs_err": null,
          "max_rel_err": null
        }
      ]
    },
    "ncu": {
      "round": 5,
      "commit": "8ee1ca1",
      "ts": "2026-03-29 06:38 UTC",
      "note": "large BF16 act GEMM2 s7",
      "source": "NCU/mar27",
      "kernels": [
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 0.03,
          "hbm_pct": null,
          "l1_pct": 37.11,
          "warp_pct": 1.58,
          "tier": "tiny",
          "seq": 1
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.1,
          "sm_pct": 6.8,
          "hbm_pct": null,
          "l1_pct": 1.15,
          "warp_pct": 6.27,
          "tier": "tiny",
          "seq": 1
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.1,
          "sm_pct": 29.82,
          "hbm_pct": null,
          "l1_pct": 1.84,
          "warp_pct": 7.33,
          "tier": "tiny",
          "seq": 1
        },
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 1.73,
          "hbm_pct": null,
          "l1_pct": 40.87,
          "warp_pct": 1.56,
          "tier": "small",
          "seq": 80
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.4,
          "sm_pct": 42.47,
          "hbm_pct": null,
          "l1_pct": 3.81,
          "warp_pct": 12.48,
          "tier": "small",
          "seq": 80
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.4,
          "sm_pct": 40.32,
          "hbm_pct": null,
          "l1_pct": 3.06,
          "warp_pct": 12.49,
          "tier": "small",
          "seq": 80
        },
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 17.53,
          "hbm_pct": null,
          "l1_pct": 54.7,
          "warp_pct": 7.74,
          "tier": "medium",
          "seq": 901
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.4,
          "sm_pct": 31.25,
          "hbm_pct": null,
          "l1_pct": 3.81,
          "warp_pct": 12.51,
          "tier": "medium",
          "seq": 901
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.6,
          "sm_pct": 40.43,
          "hbm_pct": null,
          "l1_pct": 2.91,
          "warp_pct": 24.23,
          "tier": "medium",
          "seq": 901
        },
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 72.89,
          "hbm_pct": null,
          "l1_pct": 22.68,
          "warp_pct": 68.94,
          "tier": "large",
          "seq": 14107
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.0,
          "sm_pct": 34.83,
          "hbm_pct": null,
          "l1_pct": 5.0,
          "warp_pct": 12.56,
          "tier": "large",
          "seq": 14107
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.0,
          "sm_pct": 49.01,
          "hbm_pct": null,
          "l1_pct": 1.73,
          "warp_pct": 22.15,
          "tier": "large",
          "seq": 14107
        },
        {
          "kernel_raw": "_reduce_kernel",
          "kernel": "_reduce_kernel",
          "dur_us": 0.0,
          "sm_pct": 71.83,
          "hbm_pct": null,
          "l1_pct": 19.79,
          "warp_pct": 90.26,
          "tier": "large",
          "seq": 14107
        }
      ]
    },
    "notes": "# Round 5 \u2014 large BF16 act, GEMM2 s7\n\n**Commit**: 8ee1ca1\n**Date**: 2026-03-29 06:37 UTC\n\n## Results\n\n| Tier | seq | lat(ms) | speedup | Status |\n|------|----:|--------:|--------:|--------|\n| tiny | 1 | 0.628 | 17.85x | PASSED |\n| small | 80 | 0.945 | 16.85x | PASSED |\n| medium | 901 | 1.166 | 18.12x | PASSED |\n| large | 14107 | N/A | N/A | RUNTIME_ERROR |\n\n**Avg speedup**: 17.61x\n\n## Observations\n\n_[fill in after reviewing results]_\n\n## Hypothesis for Next Run\n\n_[fill in before starting next round]_"
  },
  {
    "folder": "round_006_a399e7e_large_bf16_act_stages7",
    "config": {
      "round": 6,
      "commit": "a399e7e",
      "ts": "2026-03-29 06:43 UTC",
      "note": "large BF16 act stages=7",
      "tier": "all",
      "strategy": "optimization",
      "changes": "large BF16 act stages=7"
    },
    "results": {
      "round": 6,
      "commit": "a399e7e",
      "ts": "2026-03-29 06:43 UTC",
      "all_passed": false,
      "avg_speedup": 17.74,
      "workloads": [
        {
          "uuid": "e05c6c03",
          "tier": "tiny",
          "seq": 1,
          "status": "PASSED",
          "lat_ms": 0.6239384319782257,
          "speedup": 17.815228836512947,
          "max_abs_err": 2048.0,
          "max_rel_err": 50.90243911743164
        },
        {
          "uuid": "8f1ff9f1",
          "tier": "small",
          "seq": 80,
          "status": "PASSED",
          "lat_ms": 0.9271824007034303,
          "speedup": 17.052270685231385,
          "max_abs_err": 4096.0,
          "max_rel_err": 226.8580780029297
        },
        {
          "uuid": "1a4c6ba1",
          "tier": "medium",
          "seq": 901,
          "status": "PASSED",
          "lat_ms": 1.1508865938186645,
          "speedup": 18.359932306515233,
          "max_abs_err": 481280.0,
          "max_rel_err": 48127998427136.0
        },
        {
          "uuid": "5e8dc11c",
          "tier": "large",
          "seq": 14107,
          "status": "INCORRECT_NUMERICAL",
          "lat_ms": null,
          "speedup": null,
          "max_abs_err": 516096.0,
          "max_rel_err": 42803199475712.0
        }
      ]
    },
    "ncu": {
      "round": 6,
      "commit": "a399e7e",
      "ts": "2026-03-29 06:46 UTC",
      "note": "large BF16 act stages=7",
      "source": "NCU/mar27",
      "kernels": [
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 0.03,
          "hbm_pct": null,
          "l1_pct": 37.11,
          "warp_pct": 1.58,
          "tier": "tiny",
          "seq": 1
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.1,
          "sm_pct": 6.8,
          "hbm_pct": null,
          "l1_pct": 1.15,
          "warp_pct": 6.27,
          "tier": "tiny",
          "seq": 1
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.1,
          "sm_pct": 29.82,
          "hbm_pct": null,
          "l1_pct": 1.84,
          "warp_pct": 7.33,
          "tier": "tiny",
          "seq": 1
        },
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 1.73,
          "hbm_pct": null,
          "l1_pct": 40.87,
          "warp_pct": 1.56,
          "tier": "small",
          "seq": 80
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.4,
          "sm_pct": 42.47,
          "hbm_pct": null,
          "l1_pct": 3.81,
          "warp_pct": 12.48,
          "tier": "small",
          "seq": 80
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.4,
          "sm_pct": 40.32,
          "hbm_pct": null,
          "l1_pct": 3.06,
          "warp_pct": 12.49,
          "tier": "small",
          "seq": 80
        },
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 17.53,
          "hbm_pct": null,
          "l1_pct": 54.7,
          "warp_pct": 7.74,
          "tier": "medium",
          "seq": 901
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.4,
          "sm_pct": 31.25,
          "hbm_pct": null,
          "l1_pct": 3.81,
          "warp_pct": 12.51,
          "tier": "medium",
          "seq": 901
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.6,
          "sm_pct": 40.43,
          "hbm_pct": null,
          "l1_pct": 2.91,
          "warp_pct": 24.23,
          "tier": "medium",
          "seq": 901
        },
        {
          "kernel_raw": "_fused_routing_kernel",
          "kernel": "_fused_routing_kernel",
          "dur_us": 0.0,
          "sm_pct": 72.89,
          "hbm_pct": null,
          "l1_pct": 22.68,
          "warp_pct": 68.94,
          "tier": "large",
          "seq": 14107
        },
        {
          "kernel_raw": "_gemm1_swiglu_kernel",
          "kernel": "_gemm1_swiglu_kernel",
          "dur_us": 0.0,
          "sm_pct": 34.83,
          "hbm_pct": null,
          "l1_pct": 5.0,
          "warp_pct": 12.56,
          "tier": "large",
          "seq": 14107
        },
        {
          "kernel_raw": "_gemm2_kernel",
          "kernel": "_gemm2_kernel",
          "dur_us": 0.0,
          "sm_pct": 49.01,
          "hbm_pct": null,
          "l1_pct": 1.73,
          "warp_pct": 22.15,
          "tier": "large",
          "seq": 14107
        },
        {
          "kernel_raw": "_reduce_kernel",
          "kernel": "_reduce_kernel",
          "dur_us": 0.0,
          "sm_pct": 71.83,
          "hbm_pct": null,
          "l1_pct": 19.79,
          "warp_pct": 90.26,
          "tier": "large",
          "seq": 14107
        }
      ]
    },
    "notes": "# Round 6 \u2014 large BF16 act stages=7\n\n**Commit**: a399e7e\n**Date**: 2026-03-29 06:43 UTC\n\n## Results\n\n| Tier | seq | lat(ms) | speedup | Status |\n|------|----:|--------:|--------:|--------|\n| tiny | 1 | 0.624 | 17.82x | PASSED |\n| small | 80 | 0.927 | 17.05x | PASSED |\n| medium | 901 | 1.151 | 18.36x | PASSED |\n| large | 14107 | N/A | N/A | INCORRECT_NUMERICAL |\n\n**Avg speedup**: 17.74x\n\n## Observations\n\n_[fill in after reviewing results]_\n\n## Hypothesis for Next Run\n\n_[fill in before starting next round]_"
  },
  {
    "folder": "round_007_cf98dd2_large_gemm1_bk64_reduce_reg_pressure_ta",
    "config": {
      "round": 7,
      "commit": "cf98dd2",
      "ts": "2026-03-29 23:31 UTC",
      "note": "large GEMM1 BK=64 reduce reg pressure target 2 CTAs/SM",
      "tier": "all",
      "strategy": "optimization",
      "changes": "large GEMM1 BK=64 reduce reg pressure target 2 CTAs/SM"
    },
    "results": {
      "round": 7,
      "commit": "cf98dd2",
      "ts": "2026-03-29 23:31 UTC",
      "all_passed": true,
      "avg_speedup": 8.1,
      "workloads": [
        {
          "uuid": "5e8dc11c",
          "tier": "large",
          "seq": 14107,
          "status": "PASSED",
          "lat_ms": 5.555416646003723,
          "speedup": 8.099602231331998,
          "max_abs_err": 540672.0,
          "max_rel_err": 48947200524288.0
        }
      ]
    },
    "ncu": {},
    "notes": "# Round 7 \u2014 large GEMM1 BK=64 reduce reg pressure target 2 CTAs/SM\n\n**Commit**: cf98dd2\n**Date**: 2026-03-29 23:31 UTC\n\n## Results\n\n| Tier | seq | lat(ms) | speedup | Status |\n|------|----:|--------:|--------:|--------|\n| large | 14107 | 5.555 | 8.10x | PASSED |\n\n**Avg speedup**: 8.10x\n\n## Observations\n\n_[fill in after reviewing results]_\n\n## Hypothesis for Next Run\n\n_[fill in before starting next round]_"
  },
  {
    "folder": "round_008_7b7a583_large_stream_overlap_prefetch_tm2",
    "config": {
      "round": 8,
      "commit": "7b7a583",
      "ts": "2026-03-29 23:33 UTC",
      "note": "large stream overlap prefetch_tm2",
      "tier": "all",
      "strategy": "optimization",
      "changes": "large stream overlap prefetch_tm2"
    },
    "results": {
      "round": 8,
      "commit": "7b7a583",
      "ts": "2026-03-29 23:33 UTC",
      "all_passed": true,
      "avg_speedup": 9.01,
      "workloads": [
        {
          "uuid": "5e8dc11c",
          "tier": "large",
          "seq": 14107,
          "status": "PASSED",
          "lat_ms": 4.980015358924865,
          "speedup": 9.00518707433612,
          "max_abs_err": 581632.0,
          "max_rel_err": 47718399475712.0
        }
      ]
    },
    "ncu": {},
    "notes": "# Round 8 \u2014 large stream overlap prefetch_tm2\n\n**Commit**: 7b7a583\n**Date**: 2026-03-29 23:33 UTC\n\n## Results\n\n| Tier | seq | lat(ms) | speedup | Status |\n|------|----:|--------:|--------:|--------|\n| large | 14107 | 4.980 | 9.01x | PASSED |\n\n**Avg speedup**: 9.01x\n\n## Observations\n\n_[fill in after reviewing results]_\n\n## Hypothesis for Next Run\n\n_[fill in before starting next round]_"
  },
  {
    "folder": "round_009_51b2b3c_large_gemm2_bk32_stages3_target_3_ctas",
    "config": {
      "round": 9,
      "commit": "51b2b3c",
      "ts": "2026-03-29 23:35 UTC",
      "note": "large GEMM2 BK=32 stages=3 target 3 CTAs/SM",
      "tier": "all",
      "strategy": "optimization",
      "changes": "large GEMM2 BK=32 stages=3 target 3 CTAs/SM"
    },
    "results": {
      "round": 9,
      "commit": "51b2b3c",
      "ts": "2026-03-29 23:35 UTC",
      "all_passed": true,
      "avg_speedup": 8.31,
      "workloads": [
        {
          "uuid": "5e8dc11c",
          "tier": "large",
          "seq": 14107,
          "status": "PASSED",
          "lat_ms": 5.424592959403992,
          "speedup": 8.307863552984182,
          "max_abs_err": 565248.0,
          "max_rel_err": 47923198951424.0
        }
      ]
    },
    "ncu": {},
    "notes": "# Round 9 \u2014 large GEMM2 BK=32 stages=3 target 3 CTAs/SM\n\n**Commit**: 51b2b3c\n**Date**: 2026-03-29 23:35 UTC\n\n## Results\n\n| Tier | seq | lat(ms) | speedup | Status |\n|------|----:|--------:|--------:|--------|\n| large | 14107 | 5.425 | 8.31x | PASSED |\n\n**Avg speedup**: 8.31x\n\n## Observations\n\n_[fill in after reviewing results]_\n\n## Hypothesis for Next Run\n\n_[fill in before starting next round]_"
  },
  {
    "folder": "round_010_60a390f_large_fuse_gemm2reduce_no_g2o_buffer",
    "config": {
      "round": 10,
      "commit": "60a390f",
      "ts": "2026-03-29 23:37 UTC",
      "note": "large fuse GEMM2+reduce no g2o buffer",
      "tier": "all",
      "strategy": "optimization",
      "changes": "large fuse GEMM2+reduce no g2o buffer"
    },
    "results": {
      "round": 10,
      "commit": "60a390f",
      "ts": "2026-03-29 23:37 UTC",
      "all_passed": true,
      "avg_speedup": 8.66,
      "workloads": [
        {
          "uuid": "5e8dc11c",
          "tier": "large",
          "seq": 14107,
          "status": "PASSED",
          "lat_ms": 5.1911592264175415,
          "speedup": 8.66350697767645,
          "max_abs_err": 598016.0,
          "max_rel_err": 59801602097152.0
        }
      ]
    },
    "ncu": {},
    "notes": "# Round 10 \u2014 large fuse GEMM2+reduce no g2o buffer\n\n**Commit**: 60a390f\n**Date**: 2026-03-29 23:37 UTC\n\n## Results\n\n| Tier | seq | lat(ms) | speedup | Status |\n|------|----:|--------:|--------:|--------|\n| large | 14107 | 5.191 | 8.66x | PASSED |\n\n**Avg speedup**: 8.66x\n\n## Observations\n\n_[fill in after reviewing results]_\n\n## Hypothesis for Next Run\n\n_[fill in before starting next round]_"
  },
  {
    "folder": "round_011_ce0f05c_large_fp8_act_gemm1_fp8out_gemm2_fp8xfp8",
    "config": {
      "round": 11,
      "commit": "ce0f05c",
      "ts": "2026-03-29 23:55 UTC",
      "note": "large FP8 act GEMM1 fp8out GEMM2 fp8xfp8",
      "tier": "all",
      "strategy": "optimization",
      "changes": "large FP8 act GEMM1 fp8out GEMM2 fp8xfp8"
    },
    "results": {
      "round": 11,
      "commit": "ce0f05c",
      "ts": "2026-03-29 23:55 UTC",
      "all_passed": false,
      "avg_speedup": 0.0,
      "workloads": [
        {
          "uuid": "5e8dc11c",
          "tier": "large",
          "seq": 14107,
          "status": "INCORRECT_NUMERICAL",
          "lat_ms": null,
          "speedup": null,
          "max_abs_err": 509952.0,
          "max_rel_err": 43212798427136.0
        }
      ]
    },
    "ncu": {},
    "notes": "# Round 11 \u2014 large FP8 act GEMM1 fp8out GEMM2 fp8xfp8\n\n**Commit**: ce0f05c\n**Date**: 2026-03-29 23:55 UTC\n\n## Results\n\n| Tier | seq | lat(ms) | speedup | Status |\n|------|----:|--------:|--------:|--------|\n| large | 14107 | N/A | N/A | INCORRECT_NUMERICAL |\n\n**Avg speedup**: 0.00x\n\n## Observations\n\n_[fill in after reviewing results]_\n\n## Hypothesis for Next Run\n\n_[fill in before starting next round]_"
  },
  {
    "folder": "round_012_943905e_large_gemm1_bk64_stages1_target_2_ctas",
    "config": {
      "round": 12,
      "commit": "943905e",
      "ts": "2026-03-30 00:00 UTC",
      "note": "large GEMM1 BK=64 stages=1 target 2 CTAs/SM via reduced addr regs",
      "tier": "all",
      "strategy": "optimization",
      "changes": "large GEMM1 BK=64 stages=1 target 2 CTAs/SM via reduced addr regs"
    },
    "results": {
      "round": 12,
      "commit": "943905e",
      "ts": "2026-03-30 00:00 UTC",
      "all_passed": true,
      "avg_speedup": 5.45,
      "workloads": [
        {
          "uuid": "5e8dc11c",
          "tier": "large",
          "seq": 14107,
          "status": "PASSED",
          "lat_ms": 8.288605815887452,
          "speedup": 5.45386796189786,
          "max_abs_err": 491520.0,
          "max_rel_err": 46489598427136.0
        }
      ]
    },
    "ncu": {},
    "notes": "# Round 12 \u2014 large GEMM1 BK=64 stages=1 target 2 CTAs/SM via reduced addr regs\n\n**Commit**: 943905e\n**Date**: 2026-03-30 00:00 UTC\n\n## Results\n\n| Tier | seq | lat(ms) | speedup | Status |\n|------|----:|--------:|--------:|--------|\n| large | 14107 | 8.289 | 5.45x | PASSED |\n\n**Avg speedup**: 5.45x\n\n## Observations\n\n_[fill in after reviewing results]_\n\n## Hypothesis for Next Run\n\n_[fill in before starting next round]_"
  },
  {
    "folder": "round_013_4995b04_large_gemm2_bn64_bk64_stages3_target_",
    "config": {
      "round": 13,
      "commit": "4995b04",
      "ts": "2026-03-30 00:02 UTC",
      "note": "large GEMM2 BN=64 BK=64 stages=3 target 3 CTAs/SM",
      "tier": "all",
      "strategy": "optimization",
      "changes": "large GEMM2 BN=64 BK=64 stages=3 target 3 CTAs/SM"
    },
    "results": {
      "round": 13,
      "commit": "4995b04",
      "ts": "2026-03-30 00:02 UTC",
      "all_passed": true,
      "avg_speedup": 6.37,
      "workloads": [
        {
          "uuid": "5e8dc11c",
          "tier": "large",
          "seq": 14107,
          "status": "PASSED",
          "lat_ms": 7.061864327430724,
          "speedup": 6.3711448765292005,
          "max_abs_err": 518144.0,
          "max_rel_err": 51814401572864.0
        }
      ]
    },
    "ncu": {},
    "notes": "# Round 13 \u2014 large GEMM2 BN=64 BK=64 stages=3 target 3 CTAs/SM\n\n**Commit**: 4995b04\n**Date**: 2026-03-30 00:02 UTC\n\n## Results\n\n| Tier | seq | lat(ms) | speedup | Status |\n|------|----:|--------:|--------:|--------|\n| large | 14107 | 7.062 | 6.37x | PASSED |\n\n**Avg speedup**: 6.37x\n\n## Observations\n\n_[fill in after reviewing results]_\n\n## Hypothesis for Next Run\n\n_[fill in before starting next round]_"
  },
  {
    "folder": "round_014_2e7bb9c_medium_baseline_check",
    "config": {
      "round": 14,
      "commit": "2e7bb9c",
      "ts": "2026-03-30 00:03 UTC",
      "note": "medium baseline check",
      "tier": "all",
      "strategy": "optimization",
      "changes": "medium baseline check"
    },
    "results": {
      "round": 14,
      "commit": "2e7bb9c",
      "ts": "2026-03-30 00:03 UTC",
      "all_passed": true,
      "avg_speedup": 18.33,
      "workloads": [
        {
          "uuid": "1a4c6ba1",
          "tier": "medium",
          "seq": 901,
          "status": "PASSED",
          "lat_ms": 1.1499178221225739,
          "speedup": 18.328555360075278,
          "max_abs_err": 428032.0,
          "max_rel_err": 27033600000000.0
        }
      ]
    },
    "ncu": {},
    "notes": "# Round 14 \u2014 medium baseline check\n\n**Commit**: 2e7bb9c\n**Date**: 2026-03-30 00:03 UTC\n\n## Results\n\n| Tier | seq | lat(ms) | speedup | Status |\n|------|----:|--------:|--------:|--------|\n| medium | 901 | 1.150 | 18.33x | PASSED |\n\n**Avg speedup**: 18.33x\n\n## Observations\n\n_[fill in after reviewing results]_\n\n## Hypothesis for Next Run\n\n_[fill in before starting next round]_"
  },
  {
    "folder": "round_015_2e7bb9c_small_baseline_check",
    "config": {
      "round": 15,
      "commit": "2e7bb9c",
      "ts": "2026-03-30 00:06 UTC",
      "note": "small baseline check",
      "tier": "all",
      "strategy": "optimization",
      "changes": "small baseline check"
    },
    "results": {
      "round": 15,
      "commit": "2e7bb9c",
      "ts": "2026-03-30 00:06 UTC",
      "all_passed": true,
      "avg_speedup": 18.13,
      "workloads": [
        {
          "uuid": "8f1ff9f1",
          "tier": "small",
          "seq": 80,
          "status": "PASSED",
          "lat_ms": 0.8730309113264084,
          "speedup": 18.126291651659656,
          "max_abs_err": 4096.0,
          "max_rel_err": 987.8623657226562
        }
      ]
    },
    "ncu": {},
    "notes": "# Round 15 \u2014 small baseline check\n\n**Commit**: 2e7bb9c\n**Date**: 2026-03-30 00:06 UTC\n\n## Results\n\n| Tier | seq | lat(ms) | speedup | Status |\n|------|----:|--------:|--------:|--------|\n| small | 80 | 0.873 | 18.13x | PASSED |\n\n**Avg speedup**: 18.13x\n\n## Observations\n\n_[fill in after reviewing results]_\n\n## Hypothesis for Next Run\n\n_[fill in before starting next round]_"
  },
  {
    "folder": "round_016_2e7bb9c_medium_gemm1_stages3-4_smem_72-96kb-",
    "config": {
      "round": 16,
      "commit": "2e7bb9c",
      "ts": "2026-03-30 00:10 UTC",
      "note": "medium GEMM1 stages=3->4 (smem 72->96KB/CTA, 2CTAs/SM=192KB<232KB)",
      "tier": "all",
      "strategy": "optimization",
      "changes": "medium GEMM1 stages=3->4 (smem 72->96KB/CTA, 2CTAs/SM=192KB<232KB)"
    },
    "results": {
      "round": 16,
      "commit": "2e7bb9c",
      "ts": "2026-03-30 00:10 UTC",
      "all_passed": true,
      "avg_speedup": 18.46,
      "workloads": [
        {
          "uuid": "1a4c6ba1",
          "tier": "medium",
          "seq": 901,
          "status": "PASSED",
          "lat_ms": 1.1416927361488343,
          "speedup": 18.457359443746807,
          "max_abs_err": 409600.0,
          "max_rel_err": 31334399475712.0
        }
      ]
    },
    "ncu": {},
    "notes": "# Round 16 \u2014 medium GEMM1 stages=3->4 (smem 72->96KB/CTA, 2CTAs/SM=192KB<232KB)\n\n**Commit**: 2e7bb9c\n**Date**: 2026-03-30 00:10 UTC\n\n## Results\n\n| Tier | seq | lat(ms) | speedup | Status |\n|------|----:|--------:|--------:|--------|\n| medium | 901 | 1.142 | 18.46x | PASSED |\n\n**Avg speedup**: 18.46x\n\n## Observations\n\n_[fill in after reviewing results]_\n\n## Hypothesis for Next Run\n\n_[fill in before starting next round]_"
  },
  {
    "folder": "round_017_2e7bb9c_medium_gemm1_s4_gemm2_stages8-9_smem_",
    "config": {
      "round": 17,
      "commit": "2e7bb9c",
      "ts": "2026-03-30 00:11 UTC",
      "note": "medium GEMM1 s4 GEMM2 stages=8->9 (smem 108KB/CTA, 2CTAs=216KB<232KB)",
      "tier": "all",
      "strategy": "optimization",
      "changes": "medium GEMM1 s4 GEMM2 stages=8->9 (smem 108KB/CTA, 2CTAs=216KB<232KB)"
    },
    "results": {
      "round": 17,
      "commit": "2e7bb9c",
      "ts": "2026-03-30 00:11 UTC",
      "all_passed": true,
      "avg_speedup": 18.27,
      "workloads": [
        {
          "uuid": "1a4c6ba1",
          "tier": "medium",
          "seq": 901,
          "status": "PASSED",
          "lat_ms": 1.1561500787734986,
          "speedup": 18.267883107326668,
          "max_abs_err": 418560.0,
          "max_rel_err": 35225602097152.0
        }
      ]
    },
    "ncu": {},
    "notes": "# Round 17 \u2014 medium GEMM1 s4 GEMM2 stages=8->9 (smem 108KB/CTA, 2CTAs=216KB<232KB)\n\n**Commit**: 2e7bb9c\n**Date**: 2026-03-30 00:11 UTC\n\n## Results\n\n| Tier | seq | lat(ms) | speedup | Status |\n|------|----:|--------:|--------:|--------|\n| medium | 901 | 1.156 | 18.27x | PASSED |\n\n**Avg speedup**: 18.27x\n\n## Observations\n\n_[fill in after reviewing results]_\n\n## Hypothesis for Next Run\n\n_[fill in before starting next round]_"
  },
  {
    "folder": "round_018_2e7bb9c_medium_gemm1_s4_gemm2_bk32-64_stages8",
    "config": {
      "round": 18,
      "commit": "2e7bb9c",
      "ts": "2026-03-30 00:12 UTC",
      "note": "medium GEMM1 s4 GEMM2 BK=32->64 stages=8->4 (smem 96KB/CTA 2CTAs=192KB)",
      "tier": "all",
      "strategy": "optimization",
      "changes": "medium GEMM1 s4 GEMM2 BK=32->64 stages=8->4 (smem 96KB/CTA 2CTAs=192KB)"
    },
    "results": {
      "round": 18,
      "commit": "2e7bb9c",
      "ts": "2026-03-30 00:12 UTC",
      "all_passed": true,
      "avg_speedup": 19.19,
      "workloads": [
        {
          "uuid": "1a4c6ba1",
          "tier": "medium",
          "seq": 901,
          "status": "PASSED",
          "lat_ms": 1.113619518995285,
          "speedup": 19.192099811371666,
          "max_abs_err": 389120.0,
          "max_rel_err": 38912001048576.0
        }
      ]
    },
    "ncu": {},
    "notes": "# Round 18 \u2014 medium GEMM1 s4 GEMM2 BK=32->64 stages=8->4 (smem 96KB/CTA 2CTAs=192KB)\n\n**Commit**: 2e7bb9c\n**Date**: 2026-03-30 00:12 UTC\n\n## Results\n\n| Tier | seq | lat(ms) | speedup | Status |\n|------|----:|--------:|--------:|--------|\n| medium | 901 | 1.114 | 19.19x | PASSED |\n\n**Avg speedup**: 19.19x\n\n## Observations\n\n_[fill in after reviewing results]_\n\n## Hypothesis for Next Run\n\n_[fill in before starting next round]_"
  }
];
