"""
Regenerate dashboard_data.js by scanning all experiments/round_*/ folders.

Run after every benchmark or profiling update:
    python scripts/update_dashboard_data.py

Each experiments/round_NNN_<commit>_<slug>/ folder must contain:
    config.json      - {round, commit, ts, note, tier, strategy, changes}
    results.json     - {workloads: [{uuid, tier, seq, status, lat_ms, speedup, ...}]}
    ncu_metrics.json - {kernels: [{tier, seq, kernel, dur_us, sm_pct, ...}]}  (optional)
    notes.md         - free-form observations (optional)
"""

import json
import re
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).parent.parent
EXPERIMENTS_DIR = PROJECT_ROOT / "experiments"


def load_experiment(folder: Path) -> dict | None:
    config_path = folder / "config.json"
    results_path = folder / "results.json"
    if not config_path.exists() or not results_path.exists():
        return None

    try:
        config  = json.loads(config_path.read_text(encoding="utf-8"))
        results = json.loads(results_path.read_text(encoding="utf-8"))
    except Exception as e:
        print(f"  [WARN] Could not load {folder.name}: {e}")
        return None

    ncu = {}
    ncu_path = folder / "ncu_metrics.json"
    if ncu_path.exists():
        try:
            ncu = json.loads(ncu_path.read_text(encoding="utf-8"))
        except Exception:
            pass

    notes = ""
    notes_path = folder / "notes.md"
    if notes_path.exists():
        notes = notes_path.read_text(encoding="utf-8")

    return {
        "folder":   folder.name,
        "config":   config,
        "results":  results,
        "ncu":      ncu,
        "notes":    notes,
    }


def main():
    if not EXPERIMENTS_DIR.exists():
        print(f"[ERROR] {EXPERIMENTS_DIR} does not exist. Create it first.")
        sys.exit(1)

    # Collect all round folders, sorted by round number
    folders = sorted(
        [d for d in EXPERIMENTS_DIR.iterdir() if d.is_dir() and d.name.startswith("round_")],
        key=lambda d: int(re.match(r"round_(\d+)", d.name).group(1)) if re.match(r"round_(\d+)", d.name) else 9999
    )

    experiments = []
    for folder in folders:
        exp = load_experiment(folder)
        if exp:
            experiments.append(exp)
            r = exp["config"].get("round", "?")
            n = len(exp["results"].get("workloads", []))
            nk = len(exp["ncu"].get("kernels", []))
            print(f"  round_{r:03d}  {folder.name}  ->  {n} workloads, {nk} NCU kernels")

    out_path = PROJECT_ROOT / "dashboard_data.js"
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("// Auto-generated by scripts/update_dashboard_data.py — do not edit manually\n")
        fh.write(f"window.EXPERIMENTS = {json.dumps(experiments, indent=2)};\n")

    print(f"\nWritten {out_path}  ({len(experiments)} experiments)")


if __name__ == "__main__":
    main()
